apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kvr1672m2-go-gitops
  description: This is GitOps manifest for kvr1672m2-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=kvr1672m2-go
    backstage.io/kubernetes-id: kvr1672m2-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: kvr1672m2-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:kvr1672m2-go
