apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kvr1672m2-go
  janus-idp.io/tekton: kvr1672m2-go
  backstage.io/kubernetes-id: kvr1672m2-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kvr1672m2-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
